name: Quiz
description: Public quiz with prizes
author: StarTux
version: 0.1
api-version: 1.13
website: http://cavetale.com
main: com.winthier.quiz.QuizPlugin
depend: [ PlayerCache ]
commands:
  quiz:
    description: Quiz interface
    permission: quiz.quiz
    usage: |-
      /quiz optout - Opt out
      /quiz optin - Opt back in
      /quiz hi - Highscore
  quizadmin:
    description: Admin interface
    permission: quiz.admin
    usage: /<command> list|clear|tick|activate|prize|reload
permissions:
  quiz.quiz:
    description: Click chat to claim a prize
    default: true
  quiz.admin:
    description: Use the admin interface
    default: op